### ISSUE TITLE
Dataset about camvid

### ISSUE THREAD

**Issue by AlanSky815** [CuZaoo/SANet-main#1]
EXCUSE ME, When I download the camvid dataset,  I find the list of camvid (\data\list\camvid) has wrong serial number about annotation.  As the serial num of annotation in camvid format like : 0001TP_006870_L.png, but the download camvid annotation formation like : 0001TP_007860.
So could you please provide the correct dataset list. or provide the your dataset download link. Many thanks.

**Comment by CuZaoo** [comment]
In the screenshot, the specific download locations for Image and Label are marked respectively

![image](https://github.com/CuZaoo/SANet-main/assets/39364400/80f132f6-398c-455e-9d3e-00cd45ac4249)

**Comment by CuZaoo** [comment]
> EXCUSE ME, When I download the camvid dataset, I find the list of camvid (\data\list\camvid) has wrong serial number about annotation. As the serial num of annotation in camvid format like : 0001TP_006870_L.png, but the download camvid annotation formation like : 0001TP_007860. So could you please provide the correct dataset list. or provide the your dataset download link. Many thanks.

Thank you for asking the question. My Camvid dataset seems to be downloaded from this link
[Camvid](http://web4.cs.ucl.ac.uk/staff/g.brostow/MotionSegRecData/)
and should work straight away once downloaded. This link will also be updated to the README

**Comment by AlanSky815** [comment]
Thank you, the question has been solved.
